import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { UserButton } from "@clerk/nextjs";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex justify-end pr-5 pt-5">
          <UserButton />
        </div>
      </main>
    </>
  );
};

export default Home;
